---
# Local Path Provisioner - Lightweight storage for Jetson Nano
apiVersion: v1
kind: Namespace
metadata:
  name: storage-system
---
# Local Storage Class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
# Low-resource Longhorn Storage for persistent data
# Note: This is a simplified version for Jetson Nano
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
---
# PersistentVolume for ML model storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-models-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/ml-models
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jetson-nano
---
# PersistentVolumeClaim for ML model storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
---
# PersistentVolume for ROS 2 data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ros2-data-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/ros2-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - jetson-nano
---
# PersistentVolumeClaim for ROS 2 data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ros2-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi
